services:
  pokemon_scraper:
    image: ghcr.io/twally3/pokemon_scraper:latest
    build: .
    environment:
      - WEB_DRIVER_URL=http://selenium:4444
      - SCRAPER_SLEEP_SECS=7200
    ports:
      - 3000:3000
    volumes:
      - pokemon_scraper_db:/usr/src/app/db
      - pokemon_scraper_screenshots:/usr/src/app/screenshots
    depends_on:
      - selenium
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 30s
    networks:
      - main
    # depends_on:
    #   selenium:
    #     condition: service_healthy

  # http://localhost:7900/?autoconnect=1&resize=scale&password=secret
  selenium:
    image: seleniarm/standalone-chromium
    ports:
      - 4444:4444
      - 7900:7900
    # shm_size: 2g
    tmpfs:
      - /dev/shm:rw,nosuid,nodev,noexec,relatime,size=2g
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 2147483648  # 2GB in bytes
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:4444/status"]
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 30s
    # environment:
    #   - SE_NODE_MAX_SESSIONS=5
    #   - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    networks:
      - main

volumes:
  pokemon_scraper_db:
  pokemon_scraper_screenshots:

networks:
  main:
