services:
  pokemon_scraper:
    build: .
    environment:
      - WEB_DRIVER_URL=http://selenium:4444
      - SCRAPER_SLEEP_SECS=7200
    ports:
      - 3000:3000
    volumes:
      - pokemon_scraper:/usr/src/app/db
    depends_on:
      selenium:
        condition: service_healthy

  # http://localhost:7900/?autoconnect=1&resize=scale&password=secret
  selenium:
    image: seleniarm/standalone-chromium
    ports:
      - 4444:4444
      - 7900:7900
    shm_size: 2g
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:4444/status"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  pokemon_scraper:
